set dotenv-load := true
set shell := ["bash", "-c"]

# ── Dev environment ────────────────────────────────────────────────────────────

# Start all local infrastructure (postgres, redis, rustfs, nats, clamav)
dev:
    docker compose up -d
    @echo ""
    @echo "  IAM PostgreSQL      → localhost:5433"
    @echo "  FileNest PostgreSQL → localhost:5434"
    @echo "  Redis               → localhost:6379"
    @echo "  RustFS API          → localhost:9000   (console: http://localhost:9001)"
    @echo "  NATS                → localhost:4222   (monitor: http://localhost:8222)"
    @echo "  ClamAV              → localhost:3310"
    @echo ""

# Stop all infrastructure
down:
    docker compose down

# Stop and wipe all volumes (full reset)
reset:
    docker compose down -v

# Show logs (optionally for a specific service: just logs postgres)
logs service="":
    docker compose logs -f {{ service }}

# ── Backend ────────────────────────────────────────────────────────────────────

# Install all Python dependencies
install:
    cd backend && uv sync

# Run the FastAPI backend (hot-reload)
backend:
    cd backend && uv run uvicorn app.main:app --reload --port 8000 --log-level debug --reload-exclude ".venv"

# ── Database ───────────────────────────────────────────────────────────────────

# Apply all pending migrations
migrate:
    cd backend && uv run alembic -c migrations/alembic.ini upgrade head

# Roll back one migration
migrate-down:
    cd backend && uv run alembic -c migrations/alembic.ini downgrade -1

# Create a new autogenerated migration
migration name:
    cd backend && uv run alembic -c migrations/alembic.ini revision --autogenerate -m "{{ name }}"

# Show current DB revision
migrate-current:
    cd backend && uv run alembic -c migrations/alembic.ini current

# Show migration history
migrate-history:
    cd backend && uv run alembic -c migrations/alembic.ini history --verbose

# Check if migrations are up to date (exits non-zero if pending)
migrate-check:
    cd backend && uv run alembic -c migrations/alembic.ini check

# Drop all tables and re-apply migrations from scratch (dev only)
db-reset:
    cd backend && uv run alembic -c migrations/alembic.ini downgrade base
    cd backend && uv run alembic -c migrations/alembic.ini upgrade head

# Seed the dev database with a test project (run once after migrate)
seed-dev:
    cd backend && uv run python scripts/seed_dev.py

# ── Quality ────────────────────────────────────────────────────────────────────

# Run all tests
test:
    cd backend && uv run pytest tests/ -v

# Run tests with coverage
test-cov:
    cd backend && uv run pytest tests/ -v --cov=app --cov-report=term-missing

# Lint
lint:
    cd backend && uv run ruff check .

# Format
fmt:
    cd backend && uv run ruff format .

# Type check
types:
    cd backend && uv run pyright .

# ── SDKs ───────────────────────────────────────────────────────────────────────

# Build all SDK packages (required before running examples)
build-sdks:
    pnpm --filter @filenest/core build
    pnpm --filter @filenest/node build
    pnpm --filter @filenest/react build
    pnpm --filter @filenest/nextjs build

# Run the Next.js SDK example (port 3001)
example-nextjs:
    cd examples/nextjs-sdk && pnpm dev

# ── Frontend ───────────────────────────────────────────────────────────────────

# Run the console app (hot-reload)
web:
    cd frontend/web && pnpm dev

# Install console app dependencies
web-install:
    cd frontend/web && pnpm install

# ── IAM ────────────────────────────────────────────────────────────────────────

# Run the IAM (hot-reload)
iam:
    cd iam && pnpm dev

# ── Shortcuts ──────────────────────────────────────────────────────────────────

# Open RustFS web console in browser
storage:
    open http://localhost:9001

# Open NATS monitoring in browser
nats:
    open http://localhost:8222

# Open backend API docs in browser
docs:
    open http://localhost:8000/docs
