set dotenv-load := true
set shell := ["bash", "-c"]

# ── Dev environment ────────────────────────────────────────────────────────────

# Start all local infrastructure (postgres, redis, rustfs, nats, clamav)
dev:
    docker compose up -d
    @echo ""
    @echo "  IAM PostgreSQL   → localhost:5433"
    @echo "  FileNest PostgreSQL → localhost:5434"
    @echo "  Redis            → localhost:6379"
    @echo "  RustFS API       → localhost:9000   (console: http://localhost:9001)"
    @echo "  NATS             → localhost:4222   (monitor: http://localhost:8222)"
    @echo "  ClamAV           → localhost:3310"
    @echo ""

# Stop all infrastructure
down:
    docker compose down

# Stop and wipe all volumes (full reset)
reset:
    docker compose down -v

# Show logs (optionally for a specific service: just logs postgres)
logs service="":
    docker compose logs -f {{ service }}

# ── Python services ────────────────────────────────────────────────────────────

# Install all Python dependencies
install:
    uv sync

# Run the file service (hot-reload)
file:
    uv run uvicorn services.file.main:app --reload --port 8001 --log-level debug

# Run the project service (hot-reload)
project:
    uv run uvicorn services.project.main:app --reload --port 8003 --log-level debug

# ── Database ───────────────────────────────────────────────────────────────────

# Apply all pending migrations
migrate:
    uv run alembic -c migrations/alembic/alembic.ini upgrade head

# Roll back one migration
migrate-down:
    uv run alembic -c migrations/alembic/alembic.ini downgrade -1

# Create a new autogenerated migration
migration name:
    uv run alembic -c migrations/alembic/alembic.ini revision --autogenerate -m "{{ name }}"

# Show migration history
migrate-history:
    uv run alembic -c migrations/alembic/alembic.ini history --verbose

# Seed the dev database with a test project + API key (run once after migrate)
seed-dev:
    uv run python scripts/seed_dev.py

# ── Quality ────────────────────────────────────────────────────────────────────

# Run all tests
test:
    uv run pytest tests/ -v

# Run tests with coverage
test-cov:
    uv run pytest tests/ -v --cov=services --cov=shared --cov-report=term-missing

# Lint
lint:
    uv run ruff check .

# Format
fmt:
    uv run ruff format .

# Type check
types:
    uv run pyright

# Run the console app (hot-reload)
web:
    cd frontend/web && pnpm dev

# Install console app dependencies
web-install:
    cd frontend/web && pnpm install

# ── Shortcuts ──────────────────────────────────────────────────────────────────

# Open RustFS web console in browser
storage:
    open http://localhost:9001

# Open NATS monitoring in browser
nats:
    open http://localhost:8222

# Open file service API docs in browser
docs:
    open http://localhost:8001/docs
