packages:
  - "frontend/web"
  - "iam"
  - "sdks/*"
  - "examples/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
