"""
app.models.upload_token — ORM model for the upload_tokens table.

Upload tokens are short-lived credentials issued by the server so that browser
clients can upload files without ever seeing the project's full API key.

Tokens are verified directly against this table in auth/dependencies.py.
Expired or used-beyond-max tokens are rejected at auth time.

Usage:
    from app.models.upload_token import UploadToken
"""
import secrets
import uuid
from datetime import UTC, datetime

from sqlalchemy import Column, DateTime, Integer, JSON, String

from app.core.database import Base


class UploadToken(Base):
    """
    A short-lived upload credential for browser clients.

    Generated by POST /v1/projects/{id}/upload-tokens and consumed by
    @filenest/react to authenticate file upload requests. Constraints
    (max_size, allowed_mime_types, max_files) are enforced at upload time
    by the FileService when it sees an upload-token context.
    """

    __tablename__ = "upload_tokens"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    organization_id = Column(String, nullable=False, index=True)
    project_id = Column(String, nullable=False, index=True)
    # The bearer token value returned to the caller — e.g. fn_upload_token_<hex>
    token = Column(String, nullable=False, unique=True, index=True)

    # Constraints enforced at upload time
    max_size = Column(Integer, nullable=True)       # bytes; None = no limit
    allowed_mime_types = Column(JSON, nullable=True)  # list[str]; None = all types
    max_files = Column(Integer, nullable=True)      # None = no limit

    # Optional upload defaults
    folder_id = Column(String, nullable=True)
    default_metadata = Column(JSON, nullable=True)

    # Optional owner scoping — set server-side at token creation; browser cannot override.
    # When present, FileService copies these onto every File uploaded with this token.
    owner_user_id = Column(String, nullable=True, index=True)
    owner_org_id = Column(String, nullable=True, index=True)

    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC))

    @staticmethod
    def generate_token() -> str:
        """Return a new token string with the fn_upload_token_ prefix."""
        return f"fn_upload_token_{secrets.token_hex(32)}"
