"""
app.models.webhook — ORM models for webhooks and webhook_deliveries tables.

Webhook: a customer-configured HTTP endpoint that receives signed event payloads.
WebhookDelivery: one row per delivery attempt, used for debugging and retry tracking.

Usage:
    from app.models.webhook import Webhook, WebhookDelivery
"""
import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text

from app.core.database import Base


class Webhook(Base):
    """
    A customer-configured webhook endpoint.

    events is a comma-separated list of event types to subscribe to,
    e.g. "file.ready,file.quarantined". An empty string means all events.

    signing_secret is generated by FileNest at creation time and shown once.
    The customer uses it to verify the X-FileNest-Signature header on deliveries.
    """

    __tablename__ = "webhooks"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    organization_id = Column(String, nullable=False, index=True)
    project_id = Column(String, nullable=False, index=True)
    url = Column(String, nullable=False)
    # Comma-separated event types: "file.ready,file.quarantined" or "" for all
    events = Column(Text, nullable=False, default="")
    signing_secret = Column(String, nullable=False)
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )


class WebhookDelivery(Base):
    """
    A single delivery attempt for a webhook event.

    One row is created per attempt. Retries produce additional rows with
    the same webhook_id and event_type but incrementing attempt_count.

    status: pending → success | failed
    """

    __tablename__ = "webhook_deliveries"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    webhook_id = Column(String, nullable=False, index=True)
    organization_id = Column(String, nullable=False, index=True)
    project_id = Column(String, nullable=False, index=True)
    event_type = Column(String, nullable=False)
    payload_json = Column(Text, nullable=False)
    # pending, success, failed
    status = Column(String, nullable=False, default="pending")
    attempt_count = Column(Integer, nullable=False, default=1)
    response_status_code = Column(Integer, nullable=True)
    response_body = Column(Text, nullable=True)
    # Set by WebhookWorker on failure for exponential backoff
    next_retry_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
