"""
services.file.router — HTTP route definitions for the File Service.

Routes are intentionally thin: they validate input via Pydantic schemas,
delegate to FileService for all business logic, and return a typed response.
No SQL, no storage calls, and no business rules belong here.

All routes require authentication (enforced by the `get_file_service`
dependency which calls `authenticate_request` internally). Scope checks are
performed inside each handler by calling `require_scope()`.

Registered at prefix /v1 in main.py — so final paths are:
    POST   /v1/files/upload        initiate an upload
    GET    /v1/files/{file_id}     fetch a single file
    GET    /v1/files               list files (cursor-paginated)

OpenAPI schema is auto-generated by FastAPI at /docs — do not duplicate it.
"""
from fastapi import APIRouter, Depends, Query

from shared.auth import require_scope

from .dependencies import get_file_service
from .schemas import FileListResponse, FileResponse, UploadInitRequest, UploadInitResponse
from .service import FileService

router = APIRouter(tags=["Files"])


@router.post("/files/upload", response_model=UploadInitResponse, status_code=201)
async def init_upload(
    body: UploadInitRequest,
    svc: FileService = Depends(get_file_service),
) -> UploadInitResponse:
    """
    Initiate a single-file upload and return a presigned upload URL.

    The client must PUT the file bytes directly to `upload_url` — they are not
    sent through this endpoint. Required scope: `files:upload`.
    """
    require_scope("files:upload")
    return await svc.init_upload(body)


@router.get("/files/{file_id}", response_model=FileResponse)
async def get_file(
    file_id: str,
    svc: FileService = Depends(get_file_service),
) -> FileResponse:
    """
    Fetch the full metadata record for a single file.

    Returns 404 if the file does not exist within the caller's project scope.
    Required scope: `files:read`.
    """
    require_scope("files:read")
    return await svc.get_file(file_id)


@router.get("/files", response_model=FileListResponse)
async def list_files(
    folder_id: str | None = Query(None, description="Filter to files in this folder"),
    limit: int = Query(50, ge=1, le=200, description="Page size"),
    cursor: str | None = Query(None, description="Last file id from previous page"),
    svc: FileService = Depends(get_file_service),
) -> FileListResponse:
    """
    Return a cursor-paginated list of files in the current project.

    Pass `cursor` from the previous response's `cursor` field to fetch the
    next page. A null cursor in the response means you've reached the last page.
    Required scope: `files:read`.
    """
    require_scope("files:read")
    return await svc.list_files(folder_id=folder_id, limit=limit, cursor=cursor)
