"""add_default_tags_to_upload_tokens

Revision ID: 2a86f0ba655b
Revises: 42ef2be3ae9c
Create Date: 2026-06-27 11:08:44.667862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a86f0ba655b'
down_revision: Union[str, None] = '42ef2be3ae9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_tokens', sa.Column('default_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_tokens', 'default_tags')
    # ### end Alembic commands ###
