"""add_upload_sessions

Revision ID: 3c4e7e394948
Revises: 5cb875feb9aa
Create Date: 2026-06-21 02:24:40.300456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4e7e394948'
down_revision: Union[str, None] = '5cb875feb9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('s3_upload_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_file_id'), 'upload_sessions', ['file_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_organization_id'), 'upload_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_project_id'), 'upload_sessions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sessions_project_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_organization_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_file_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
