"""add_owner_fields_to_upload_tokens_and_files

Revision ID: 42ef2be3ae9c
Revises: ad3cb776b04c
Create Date: 2026-06-25 07:48:20.154893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ef2be3ae9c'
down_revision: Union[str, None] = 'ad3cb776b04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('owner_user_id', sa.String(), nullable=True))
    op.add_column('files', sa.Column('owner_org_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_owner_org_id'), 'files', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_files_owner_user_id'), 'files', ['owner_user_id'], unique=False)
    op.add_column('upload_tokens', sa.Column('owner_user_id', sa.String(), nullable=True))
    op.add_column('upload_tokens', sa.Column('owner_org_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_upload_tokens_owner_org_id'), 'upload_tokens', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_upload_tokens_owner_user_id'), 'upload_tokens', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_tokens_owner_user_id'), table_name='upload_tokens')
    op.drop_index(op.f('ix_upload_tokens_owner_org_id'), table_name='upload_tokens')
    op.drop_column('upload_tokens', 'owner_org_id')
    op.drop_column('upload_tokens', 'owner_user_id')
    op.drop_index(op.f('ix_files_owner_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_owner_org_id'), table_name='files')
    op.drop_column('files', 'owner_org_id')
    op.drop_column('files', 'owner_user_id')
    # ### end Alembic commands ###
