"""add_sse_enabled_to_storage_configs

Revision ID: 76cd534e1a01
Revises: f8171232a7bb
Create Date: 2026-06-20 15:39:00.742195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cd534e1a01'
down_revision: Union[str, None] = 'f8171232a7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='false' backfills existing rows before the NOT NULL constraint is enforced.
    op.add_column('storage_configs', sa.Column('sse_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_configs', 'sse_enabled')
    # ### end Alembic commands ###
