"""add_category_to_files

Revision ID: 7799ea444c50
Revises: 76cd534e1a01
Create Date: 2026-06-21 01:57:07.938404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7799ea444c50'
down_revision: Union[str, None] = '76cd534e1a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'category')
    # ### end Alembic commands ###
