"""add_upload_tokens_table

Revision ID: ad3cb776b04c
Revises: 3ef2f93d8524
Create Date: 2026-06-23 20:52:26.452099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3cb776b04c'
down_revision: Union[str, None] = '3ef2f93d8524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('allowed_mime_types', sa.JSON(), nullable=True),
    sa.Column('max_files', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('default_metadata', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_tokens_organization_id'), 'upload_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_upload_tokens_project_id'), 'upload_tokens', ['project_id'], unique=False)
    op.create_index(op.f('ix_upload_tokens_token'), 'upload_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_tokens_token'), table_name='upload_tokens')
    op.drop_index(op.f('ix_upload_tokens_project_id'), table_name='upload_tokens')
    op.drop_index(op.f('ix_upload_tokens_organization_id'), table_name='upload_tokens')
    op.drop_table('upload_tokens')
    # ### end Alembic commands ###
