"""initial_schema

Revision ID: bc2b0381ef68
Revises: 
Create Date: 2026-06-19 18:20:24.320880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2b0381ef68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_organization_id'), 'files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_mode', sa.String(length=20), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('versioning_enabled', sa.Boolean(), nullable=False),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_projects_org_slug')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('storage_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('storage_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('bucket_name', sa.String(length=255), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('server_side_encryption', sa.String(length=50), nullable=False),
    sa.Column('kms_key_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'environment', name='uq_storage_configs_project_env')
    )
    op.create_index(op.f('ix_storage_configs_organization_id'), 'storage_configs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_configs_project_id'), 'storage_configs', ['project_id'], unique=False)
    op.create_table('storage_migrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_config_id', sa.String(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('target_config_id', sa.String(), nullable=False),
    sa.Column('target_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('completed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('skipped_files', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('migrated_bytes', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cutover_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_migrations_organization_id'), 'storage_migrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_migrations_project_id'), 'storage_migrations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_migrations_project_id'), table_name='storage_migrations')
    op.drop_index(op.f('ix_storage_migrations_organization_id'), table_name='storage_migrations')
    op.drop_table('storage_migrations')
    op.drop_index(op.f('ix_storage_configs_project_id'), table_name='storage_configs')
    op.drop_index(op.f('ix_storage_configs_organization_id'), table_name='storage_configs')
    op.drop_table('storage_configs')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_index(op.f('ix_files_organization_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
