"""add_tags_to_files_and_metadata_schemas

Revision ID: f46d744c39c2
Revises: 78ea4aacef65
Create Date: 2026-06-21 09:51:59.726252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f46d744c39c2'
down_revision: Union[str, None] = '78ea4aacef65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_schemas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_schemas_organization_id'), 'metadata_schemas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_metadata_schemas_project_id'), 'metadata_schemas', ['project_id'], unique=False)
    op.add_column('files', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('project_configs', sa.Column('enforce_schema', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_configs', 'enforce_schema')
    op.drop_column('files', 'tags')
    op.drop_index(op.f('ix_metadata_schemas_project_id'), table_name='metadata_schemas')
    op.drop_index(op.f('ix_metadata_schemas_organization_id'), table_name='metadata_schemas')
    op.drop_table('metadata_schemas')
    # ### end Alembic commands ###
