"""nullable_server_side_encryption

Revision ID: f8171232a7bb
Revises: 2a0f1ed95f60
Create Date: 2026-06-20 13:03:44.340726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8171232a7bb'
down_revision: Union[str, None] = '2a0f1ed95f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage_configs', 'server_side_encryption',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage_configs', 'server_side_encryption',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
